# Generated by Django 4.1.7 on 2023-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
