# Generated by Django 4.1.7 on 2023-07-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_article_likes_likedarticle_articlecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
