# Generated by Django 4.1.7 on 2023-07-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_remove_article_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="article_classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="classificationOfArticle",
                to="web.classification",
            ),
        ),
    ]
