# Generated by Django 4.1.7 on 2023-07-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_articlecomment_date_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='comment_content',
            field=models.TextField(null=True),
        ),
    ]
