# Generated by Django 4.2.2 on 2024-08-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_articlecomment_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
