# Generated by Django 4.2.2 on 2024-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
